### ISSUE TITLE
User can submit their answers

### ISSUE THREAD

**Issue by hellohien** [hnguy96/whats-cooking#1]
## ⚙️ Feature

> ##### A user can submit their answers about their preferences on a dish

## 📐 Functionality

> ##### Allow users to choose what type of meal they want and if they have a main ingredient to go off of

## 🖼️ Wireframes

![Homepage](https://user-images.githubusercontent.com/59902729/114943082-534ef380-9dfa-11eb-9f2b-0846a982bd78.png)
![Quiz 1](https://user-images.githubusercontent.com/59902729/114943091-54802080-9dfa-11eb-92f1-8181191ffe03.png)
![Quiz 2](https://user-images.githubusercontent.com/59902729/115062312-125cea80-9e9f-11eb-84a7-4fc367e3ca02.png)
![Homepage - Desktop](https://user-images.githubusercontent.com/59902729/114943101-56e27a80-9dfa-11eb-8c77-6cf9927075c1.png)
![Quiz 1 - Desktop](https://user-images.githubusercontent.com/59902729/114943107-577b1100-9dfa-11eb-8aff-08a2db3f0289.png)
![Quiz 2 - Desktop](https://user-images.githubusercontent.com/59902729/115062792-957e4080-9e9f-11eb-96f6-b2c8d5ff8ea5.png)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a home page HTML section
- [x] Add 2 HTML forms
- [x] Add a `data-view` attribute to each section
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens
- [x] Make a get request in `getRecipe()` passing in 2 parameters
- [x] Create a data model
- [x] Listen for `submit` events on form 1 and:
  - [x] store the value clicked as an argument in `getRecipeData()`
- [x] Show the next form when the Next button is clicked
- [x] Listen for `submit` events on form 2 and:
  - [x] store the value clicked as another argument in `getRecipeData()`
- [x] Test to make sure the values match your parameters
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
