### ISSUE TITLE
User can view the recommended dish

### ISSUE THREAD

**Issue by hellohien** [hnguy96/whats-cooking#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

A user can view their recommended dish

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user

Allow users to view their recommended dish and retake the quiz if they chooses

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Recipe Recommended](https://user-images.githubusercontent.com/59902729/115491398-bf739200-a214-11eb-81ac-f08203e2631c.png)
![Recipe Recommended - Desktop](https://user-images.githubusercontent.com/59902729/115491399-c0a4bf00-a214-11eb-9211-18170153692e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling div[data-view="recommendedRecipe"] to the HTML
- [x]  Add some dummy recipe in the HTML and style them to match the wireframe
- [x] Check that the page looks good on both mobile and desktop screens
- [x] Define a function that takes a single recipe object and returns a DOM tree that matches the example recipe in the HTML
- [x] In the XHR request event listener, create a DOM tree for the recommend recipe and append it to the page
- [x]  Remove the example HTML recipe once the recommended recipe is successfully being appended to the DOM on page load
- [x] Add a navigation item to the bottom of the page to retake the quiz
- [x] Clear the generated recipe data
- [x] Clean up all unnecessary styling
