### ISSUE TITLE
User can add a dish to their Favorites

### ISSUE THREAD

**Issue by hellohien** [hnguy96/whats-cooking#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Favorites](https://user-images.githubusercontent.com/59902729/115612041-aebc2e00-a29f-11eb-95b6-573652a75e21.png)
![Favorites - Desktop](https://user-images.githubusercontent.com/59902729/115612046-afed5b00-a29f-11eb-8924-13717d601b14.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update recipe generating function to include a heart icon
- [x] Add HTML for the Favorites page and a div[data-view="favorites"]
- [x] Listen for clicks on the heart icon of the rendered recipe
- [x] Toggle heart icon between gray and red when icon is clicked
- [x] Verify that when heart icon is clicked, the generated recipe is saved to local storage along with the rest of the data model on page reload
- [x] Display the favorited recipe on the Favorites page
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
