### ISSUE TITLE
User can delete an item in their Favorites

### ISSUE THREAD

**Issue by hellohien** [hnguy96/whats-cooking#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

If a user decides that they no longer want to keep a recipe saved, they should be able to remove it.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Allow users to unsave a recipe from Favorites

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Recipe Recommended (Modal)](https://user-images.githubusercontent.com/59902729/119281745-ad0dbf00-bbeb-11eb-9c3a-a8f70c9b0b91.png)
![Favorites](https://user-images.githubusercontent.com/59902729/119281748-b0a14600-bbeb-11eb-9b5c-120cb2e9d51d.png)
![Favorites (Delete Item)](https://user-images.githubusercontent.com/59902729/119281749-b1d27300-bbeb-11eb-9c1e-41716895bb60.png)
![Recipe Recommended (Modal) - Desktop](https://user-images.githubusercontent.com/59902729/119281751-b39c3680-bbeb-11eb-8800-6d034cb447aa.png)
![Favorites - Desktop](https://user-images.githubusercontent.com/59902729/119281752-b4cd6380-bbeb-11eb-98bb-9c727e91ec99.png)
![Favorites (Delete Item) - Desktop](https://user-images.githubusercontent.com/59902729/119281754-b5fe9080-bbeb-11eb-9502-8372a35c2a17.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Show modal if user clicks the heart icon more than once on the recipe generated page
- [x] Remove the recipe from the data model and the DOM tree from the Favorites page if the user clicks the heart icon from the Favorites page
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
